@startuml

package Usecase #FFAAAA {
  interface SkaffoldPreviewInterface {
    + disposable(): vscode.Disposable
  }

  class SkaffoldPreviewUsecase {
    - inputPort: SkaffoldPreviewServiceInputPort
  }

  class SkaffoldProfilePreviewUsecase {
    - inputPort: SkaffoldProfilePreviewServiceInputPort
  }

  SkaffoldPreviewInterface <|-down- SkaffoldPreviewUsecase
  SkaffoldPreviewInterface <|-down- SkaffoldProfilePreviewUsecase
}

package Service #AAFFAA {
  interface SkaffoldPreviewServiceInputPort {
    + render(panel: vscode.WebviewPanel): void
  }

  class SkaffoldPreviewService {
  }

  SkaffoldPreviewServiceInputPort <-up- SkaffoldPreviewUsecase
  SkaffoldPreviewServiceInputPort <|-down- SkaffoldPreviewService

  class SkaffoldProfilePreviewService {

  }

  SkaffoldPreviewServiceInputPort <-up- SkaffoldProfilePreviewUsecase
  SkaffoldPreviewServiceInputPort <|-down- SkaffoldProfilePreviewService
}

package Domain #FFFFAA {
  class SkaffoldRender {
    + render(): void
    + profileRender(): void
  }

}

@enduml